name:       cql-engine
version:    0.1.0.0
github:     "Chronos2005/cql-engine"
license:    BSD-3-Clause
author:     "Ross Aiden Melo"
maintainer: "rossmelo2005@gmail.com"
copyright:  "2025 Ross Aiden Melo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package:
# synopsis: Short description of your package
# category: Web

description: An interpreter for CQL, a custom, SQL-like query language for processing CSV files, built in Haskell using the Alex and Happy toolchains.

dependencies:
- base >= 4.7 && < 5
- array
- containers
- csv
- hspec
- directory
- silently
- deepseq


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  verbatim: |
    build-tool-depends:
      alex:alex,
      happy:happy

executables:
  cql-engine-exe:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cql-engine

tests:
  cql-engine-test:
    main:        Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cql-engine
